---@meta CInstance

-- Class representing a game maker object instance.
--
--You can use most if not all of the builtin game maker variables (For example `someCInstance.x`) [listed here](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Asset_Management/Instances/Instance_Variables/Instance_Variables.htm).
--
--As an alternative of using the `gm.call("function name", ...)` or gm.function_name(...)` syntax, you can also call game maker functions directly on the `CInstance` object.
--For example `someCInstance:instance_destroy()`.
--Object instance methods also work, like Step, Draw, Alarm, KeyPress etc.
--Note that `other` will always be null when using that syntax.
--
--To know the specific instance variables of a given object defined by the game, you can use `local variable_names = someCInstance:variable_instance_get_names()`
---@class (exact) CInstance
---@field id number
---@field object_index number
---@field sprite_index number
---@field image_index number
---@field image_speed number
---@field image_xscale number
---@field image_yscale number
---@field image_angle number
---@field image_alpha number
---@field image_blend number
---@field x number
---@field y number
---@field xstart number
---@field ystart number
---@field xprevious number
---@field yprevious number
---@field direction number
---@field speed number
---@field friction number
---@field gravity_direction number
---@field gravity number
---@field hspeed number
---@field vspeed number
---@field bbox number[4] array
---@field timer number[12] array
---@field layer number
---@field mask_index number
---@field m_nMouseOver number
---@field depth number
---@field i_currentdepth number
---@field object_name string



